---
type: spine

generate_cv_tags:
  topology_hints: true
  device_tags:
    - name: Campus
      value: DC1
    - name: Campus-Pod
      value: Pod1
    - name: Role
      value: Spine

spine:
  defaults:
    platform: 7280CR3A-32S
    loopback_ipv4_pool: 10.0.0.0/24
    loopback_ipv4_offset: 50
    rack: Blue_Spines

  nodes:
    - name: blue-spine1
      id: 1
      bgp_as: 65201
      mgmt_ip: 192.168.0.21/24
      structured_config:
        ptp:
          clock_identity: "00:1C:73:14:01:01"
