---
tenants:
  - name: FABRIC
    vrfs:
      - name: default
        svis:
          - id: 100
            name: Red-Media
            enabled: true
            nodes:
              - node: red-leaf1
                ip_address: 10.10.100.1/24

          - id: 200
            name: Blue-Media
            enabled: true
            nodes:
              - node: blue-leaf1
                ip_address: 10.10.200.1/24

          - id: 2222
            name: PTP-Vlan
            enabled: true
            nodes:
              - node: ptp-leaf-1
                ip_address: 10.10.1.254/24
              - node: ptp-leaf-2
                ip_address: 10.10.1.253/24
