---
type: spine

generate_cv_tags:
  topology_hints: true
  device_tags:
    - name: Campus
      value: DC1
    - name: Campus-Pod
      value: Pod1
    - name: Role
      value: Spine

spine:
  defaults:
    platform: 7280CR3A-32S
    loopback_ipv4_pool: 10.0.0.0/24
    loopback_ipv4_offset: 0
    rack: Red_Spines

  nodes:
    - name: red-spine1
      id: 1
      bgp_as: 65101
      mgmt_ip: 192.168.0.11/24
